config/routes.rb
Rails.application.routes.draw do
	root "jobs#index"
  resources :prospects do
    member do
      patch :move_to_applied
    end
  end
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_url, notice: 'Job was successfully created.' }
        format.json { render :index, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_url, notice: 'Job was successfully updated.' }
        format.json { render :index, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:link, :company, :comment, :date_applied, :heard_back, :job_title, :cover_letter_used, :resume_used, :rating, :listing_site, :technologies, :remote_possible, :location)
    end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy, :move_to_applied]

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to prospects_url, notice: 'Prospect was successfully created.' }
        format.json { render :index, status: :created, location: @prospect }
      else
        format.html { render :new }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to prospects_url, notice: 'Prospect was successfully updated.' }
        format.json { render :index, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move_to_applied
    @job = Job.new(:job_title => @prospect.job_title, :link => @prospect.link, :comment => @prospect.comment, :technologies => @prospect.technologies, :location => @prospect.location, :company => @prospect.company, :rating => @prospect.rating)

     @job.save
    @prospect.destroy
    redirect_to jobs_url
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.require(:prospect).permit(:job_title, :company, :link, :technologies, :location, :listing_site, :rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true, class: "uk-form-horizontal uk-margin-large") do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="uk-margin">
   <%= form.label(:job_title, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :job_title %>
  </div>


  <div class="uk-margin">
    <%= form.label(:company, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :company %>
  </div>
  
  <div class="uk-margin">
    <%= form.label(:link, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :link %>
  </div>

  <div class="uk-margin">
     <%= form.label(:technologies, {}, {class: 'uk-form-label'}) %>
    <%= form.text_area :technologies %>
  </div>

 <div class="uk-margin">
    <%= form.label(:location, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :location %>
  </div>


 <div class="uk-margin">
    <%= form.label(:comment, {}, {class: 'uk-form-label'}) %>
    <%= form.text_area :comment %>
  </div>

 <div class="uk-margin">
    <%= form.label(:rating, {}, {class: 'uk-form-label'}) %>
    <%= form.select( :rating, [1,2,3,4,5], {}, {class: 'uk-select-width-medium', id: 'form-horizontal-select'} )  %>
  </div>

  <div class="uk-margin">
    <%= form.label(:date_applied, {}, {class: 'uk-form-label'}) %>
    <%= form.date_select :date_applied %>
  </div>

  <div class="uk-margin">
     <%= form.label(:heard_back, {}, {class: 'uk-form-label'}) %>
    <%= form.check_box :heard_back %>
  </div>


  <div class="uk-margin">
     <%= form.label(:cover_letter_used, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :cover_letter_used %>
  </div>

  <div class="uk-margin">
     <%= form.label(:resume_used, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :resume_used %>
  </div>

  <div class="uk-margin">
     <%= form.label(:listing_site, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :listing_site %>
  </div>

  <div class="uk-margin">
     <%= form.label(:remote_possible, {}, {class: 'uk-form-label'}) %>
    <%= form.check_box :remote_possible %>
  </div>

  
  <div class="uk-margin">
      <%= form.submit 'Create Job', :class => "uk-button uk-button-default" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="uk-heading-primary">Jobs Applied For: <%=@jobs.count%></h1>

<div class="uk-overflow-auto">
  <table class="uk-table uk-table-hover uk-table-middle uk-table-divider">
    <thead >
      <tr style="background-color: #EEE">
        
        <th  style="color: white;">____</th>
        <th >Title</th>
        <th >Company</th>
        <th >Comment</th>
        <th >Date applied</th>
        <th >Rating</th>
        <th >Heard back</th>
        <th >Cover letter used</th>
        <th >Resume used</th>
        <th >Listing site</th>
        <th >Technologies</th>
        <th >Remote possible</th>
        <th >Location</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td >
            
              <div class="links">
                  <div class="edit" uk-tooltip="title: Edit Details">
                    <%= link_to edit_job_path(job) do %> 
                      <%= image_tag('edit-48.png') %>
                    <% end %>
                  </div>
                  <div class="trash" uk-tooltip="title: Delete Job">
                    <%= link_to  job, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <%= image_tag('trash-48.png') %>
                    <% end %>
                  </div>
                </div>
           
           </td>
          <td> <a class="uk-text-large" href=<%=job.link %>><%= job.job_title %></a></td>
          <td class="uk-text-large"><%= job.company %></td>
          <td class="uk-text"><%= job.comment %></td>
          <td class="uk-text"><%= job.date_applied %></td>
          <td class="uk-text-large"><%= job.rating %></td>
          <td class="uk-text"><%= job.heard_back %></td>
          <td class="uk-text"><%= job.cover_letter_used %></td>
          <td class="uk-text"><%= job.resume_used %></td>
          <td class="uk-text"><%= job.listing_site %></td>
          <td class="uk-text"><%= job.technologies %></td>
          <td class="uk-text"><%= job.remote_possible %></td>
          <td class="uk-text"><%= job.location %></td>
          
        </tr>
      <% end %>
      
    </tbody>
  
  </table>
</div>
<br>

<a class="new" href="/jobs/new"><%= image_tag('Add-32.png') %> New Job</a><br><br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @job.link %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @job.comment %>
</p>

<p>
  <strong>Date applied:</strong>
  <%= @job.date_applied %>
</p>

<p>
  <strong>Heard back:</strong>
  <%= @job.heard_back %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @job.job_title %>
</p>

<p>
  <strong>Cover letter used:</strong>
  <%= @job.cover_letter_used %>
</p>

<p>
  <strong>Resume used:</strong>
  <%= @job.resume_used %>
</p>

<p>
  <strong>Listing site:</strong>
  <%= @job.listing_site %>
</p>

<p>
  <strong>Technologies:</strong>
  <%= @job.technologies %>
</p>

<p>
  <strong>Remote possible:</strong>
  <%= @job.remote_possible %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="css/uikit.min.css" />
        <script src="js/uikit.min.js"></script>
        <script src="js/uikit-icons.min.js"></script>
  </head>

  <body>
    <nav class="uk-navbar-container" >
      <div class="uk-navbar-center" style="background-color: #EEE">
        <ul class="uk-navbar-nav">
          <li><%= link_to 'Prospects', prospects_path %><li>
          <li><%= link_to 'Jobs Applied For', jobs_path %><li>
        </ul>
        <hr>
      </div>
       
    </nav>
   
    <%= yield %>
  
  </body>
</html>

app/views/prospects/_form.html.erb
<%= form_with(model: prospect, local: true, class: "uk-form-horizontal uk-margin-large") do |form| %>
  <% if prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="uk-margin">
   <%= form.label(:job_title, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :job_title %>
  </div>

  <div class="uk-margin">
    <%= form.label(:company, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :company %>
  </div>

  <div class="uk-margin">
    <%= form.label(:link, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :link %>
  </div>

  <div class="uk-margin">
     <%= form.label(:technologies, {}, {class: 'uk-form-label'}) %>
    <%= form.text_area :technologies %>
  </div>

 <div class="uk-margin">
    <%= form.label(:location, {}, {class: 'uk-form-label'}) %>
    <%= form.text_field :location %>
  </div>


 <div class="uk-margin">
    <%= form.label(:comment, {}, {class: 'uk-form-label'}) %>
    <%= form.text_area :comment %>
  </div>

 <div class="uk-margin">
    <%= form.label(:rating, {}, {class: 'uk-form-label'}) %>
    <%= form.select( :rating, [1,2,3,4,5], {}, {class: 'uk-select-width-medium', id: 'form-horizontal-select'} )  %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Prospect', :class => "uk-button uk-button-default" %>
   
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing Prospect</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="uk-heading-primary">Prospects: <%= @prospects.count %></h1>
<div class="uk-overflow-auto">
  <table class="uk-table uk-table-hover uk-table-middle uk-table-divider">
    <thead>
      <tr style="background-color: #EEE">
        <th style="color: white">____</th>
        <th >Job title</th>
        <th >Company</th>
        <th >Technologies</th>
        <th >Location</th>
        <th >Comment</th>
        <th >Rating</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @prospects.each do |prospect| %>
        <tr>
          <td>
              <div class="links">
                <div class="edit" uk-tooltip="title: Edit Details">
                  <%= link_to edit_prospect_path(prospect) do %> 
                    <%= image_tag('edit-48.png') %>
                  <% end %>
                </div>
                <div class="trash" uk-tooltip="title: Delete Prospect">
                  <%= link_to  prospect, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <%= image_tag('trash-48.png') %>
                  <% end %>
                </div>
                <div class="apply" uk-tooltip="title: Move to 'Applied For' jobs">
                  <%= link_to move_to_applied_prospect_path(prospect), method: :patch do %>
                    <%= image_tag('arrow-48.png')%>
                  <% end %>
                </div>
              </div>
            </td>
          <td><a class="uk-text-large" href='<%= prospect.link %>'> <%= prospect.job_title %></a></td>
          <td class="uk-text"><%= prospect.company %></td>
          <td class="uk-text"><%= prospect.technologies %></td>
          <td class="uk-text"><%= prospect.location %></td>
          <td class="uk-text"><%= prospect.comment %></td>
          <td class="uk-text-large"><%= prospect.rating %></td>
          
        </tr>
        
      <% end %>
    </tbody>
  </table>
</div>
<br>

<a class="new" href="/prospects/new"><%= image_tag('Add-32.png') %> New Prospect</a><br><br>

app/views/prospects/new.html.erb
<h1>New Prospect</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job title:</strong>
  <%= @prospect.job_title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @prospect.link %>
</p>

<p>
  <strong>Technologies:</strong>
  <%= @prospect.technologies %>
</p>

<p>
  <strong>Location:</strong>
  <%= @prospect.location %>
</p>


<p>
  <strong>Comment:</strong>
  <%= @prospect.comment %>
</p>

<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>